version: "3.9"
services:
  server:
    build: .
    container_name: server
    image: socialink-api-server
    restart: always
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - SERVER_PORT=8000
      - DB_HOST=pg-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    depends_on:
      - pg-db
  pg-db:
    image: postgres:16.0
    container_name: pg-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
